name: ✅ Tests n publish

on:
  push:
    branches:
      - "**"
      - "!v*"
    tags-ignore:
      - "**"

concurrency:
  cancel-in-progress: true
  group: tests-lint-${{ github.ref_name }}

jobs:
  tests:
    name: Lint & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Yarn install
        run: |
          yarn --immutable

      - name: Yarn build
        run: |
          yarn build

      - name: Run lint
        run: yarn lint

      - name: Run unit test
        run: yarn test

      - name: Run e2e test values1.yaml
        shell: bash
        run: |
          ./bin/index.js -f .github/e2e/values1.yaml > values1.json
          diff values1.json .github/e2e/values1.schema.json
          ./bin/index.js -f .github/e2e/values2.yaml > values2.json
          diff values2.json .github/e2e/values2.schema.json

      - name: Semantic Release
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/exec
            @semantic-release/git
        env:
          GIT_AUTHOR_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SOCIALGROOVYBOT_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SOCIALGROOVYBOT_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SOCIALGROOVYBOT_NPM_TOKEN }}
